### PR TITLE
Requested dashboard fixes

### PR DESCRIPTION
**Pull request by remiolsen**
* Switch to flexbox on the external dashboard
    * (cheeky fix for smaller screens) hide the footer for screens < 1080p
* Fixed a bug in the barplot JS code
* Sorted TaT histograms on portal dashboard
* Add ongoing projects to -current year- project plot

### CODE REVIEW

**Comment by remiolsen** [comment]
Still one more thing I want to fix before this is merged... 🕚

**Comment by remiolsen** [comment]
Okay. I think this is it. Unless you have more tasks for me @ewels 😀

**Comment by ewels** [comment]
* External
  * We spoke about having currently open samples too?
  * Flexbox is great! Can we have it for vertical spacing too?
* Portal
  * Sorting is good, but sequencing-only should be top as it's most frequent
  * I think we spoke about having longer description texts for each plot - maybe as a button + drop down if people want to know more about how the numbers are generated.

**Comment by remiolsen** [comment]
Thanks. I'll take a look at scaling flexbox vertically and also the sorting of the portal plot.

And yes, we spoke about the others. Maybe I'll just make a new cards for those things and make new PR later?

**Comment by ewels** [comment]
Sounds good! I think the sorting is the main thing to adjust here, should hopefully be a quick fix.

**Comment by remiolsen** [comment]
ping @ewels. Okay `sequencing only` is now always at the top of the list.

**Review by ewels — APPROVED** [review]
👍

**Pull request merged**
