### PR TITLE
Change external dashboard to use data from last 6 months

### PR DESCRIPTION
**Pull request by remiolsen**

### CODE REVIEW

**Comment by ewels** [comment]
How have you managed to get merge conflicts..? All of the recent stuff has been from you as well! 😝

**Comment by remiolsen** [comment]
I'm as surprised as you.

**Comment by remiolsen** [comment]
"Conflict" is resolved now. I still don't know how this happened.

**Comment by ewels** [comment]
merge

**Comment by remiolsen** [comment]
Thanks. This merge seems to be more similar to:

**Pull request merged**
