### PR TITLE
Change the meaning of TaT to median days

### PR DESCRIPTION
**Pull request by remiolsen**
Already made a test update to the live dashboard check it out before 12:00

### CODE REVIEW

**Comment by ewels** [comment]
Ok nice! So you used the same variable name so it just works? Then moved the existing 90th percentile value into a new namespace?

**Comment by ewels** [comment]
Dashboard looks great!

**Comment by remiolsen** [comment]
Yup, I figured that it was the least hassle to do. Also I've deployed it on tools.

**Comment by ewels** [comment]
Brilliant, thanks! Working on front end changes now, will submit a PR shortly.

**Pull request merged**
