### PR TITLE
Fixing travis builds

### PR DESCRIPTION
**Pull request by remiolsen**

### CODE REVIEW

**Comment by ewels** [comment]
fake

**Comment by ewels** [comment]
```
The command "cd update_kpis/tests && nosetests -v -s" exited with 0.
```

Awesome! Also, you can enable Travis for your personal account and this repo too if you want - then you don't have to open a PR to get it to run. Any commit you push will trigger a build.

**Comment by remiolsen** [comment]
Oh yeah, that's what I did. 

Also:

**Comment by ewels** [comment]
Cool! Yes I tried to post that video but couldn't embed YouTube :cry:

**Pull request merged**
