### PR TITLE
Refactoring update kpis

### PR DESCRIPTION
**Pull request by remiolsen**
I hope that these changes makes sense. Instead of having and object that just does **stuff**, I've tried to break it down to an iterator and kpi objects, with some added documentation.

@ewels Does this make any sense to you?

### CODE REVIEW

**Comment by ewels** [comment]
This is huge :)

**Comment by ewels** [comment]
Ok yeah, I think I get where you're going with this. Looks pretty readable actually! I assume it's tested and it works?

**Comment by ewels** [comment]
@remiolsen: I'll leave it to you to deploy on `tools` if that's ok..

**Comment by remiolsen** [comment]
Thanks, I just wanted a sanity check. Yeah, it gave the same output as the previous version when I tested it.

**Pull request merged**
